id: A5B73CCC4
title: A S훮dhana of T훮r훮 Sarasvat카
type: translation
pechas:
- I4C970B8B
- I42A14BBE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:57.505189
  last_modified_at: 2023-01-04 11:38:57.505199
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4C970B8B/CB14: FC2C
  I42A14BBE/452E: FC2C
